# trigger 

create or replace TRIGGER CHANGETRIGGER
AFTER INSERT OR UPDATE OR DELETE ON SALRY_EMP
FOR EACH ROW
DECLARE
SALARY NUMBER; 
V_ACTION VARCHAR2(20);
V_USER VARCHAR2(200);
V_MACHINE VARCHAR2(200);
BEGIN
            IF UPDATING THEN
            V_ACTION:='UPDATING';
            ELSIF INSERTING THEN
            V_ACTION:='INSERTING';
            ELSIF DELETING THEN
            V_ACTION:='DELETING';
            END IF ;
            
            SELECT SYS_CONTEXT('USERENV','SESSION_USER'),
                           SYS_CONTEXT('USERENV','HOST')
                      INTO V_USER ,V_MACHINE FROM DUAL;
            
INSERT INTO salry_empbackup(emp_id , emp_salary , emp_dept ,ACTION, LOGINTIME, LOGINUSER, USERNAME)
VALUES (:OLD.EMP_ID, :OLD.EMP_SALARY, :OLD.EMP_DEPT,V_ACTION,SYSTIMESTAMP,V_USER,V_MACHINE);
END;

